name: "Day 8 - Debugging Workflows"

on:
  workflow_dispatch:

jobs:
  broken-job:
    runs-on: ubuntu-latest
    steps:
      - name: This step will work
        run: echo "Step 1 is fine!"

      - name: This step will BREAK
        continue-on-error: true
        run: eccho "This command is wrong!" # Fixed 'eccho' to 'echo'

      - name: This step will run now
        run: echo "I will run because the previous step has continue-on-error!"